### ISSUE TITLE
Generate reproducible blockchain bootstraps

### ISSUE THREAD

**Issue by catbref** [Qortal/qortal#1]
This is so new users don't have to sync but can simply download a verifiable copy of the blockchain.

Two ways to potentially do this:
1. Write a separate app that uses copy of database, rolls back to nearest 1000 height (this requires CPU)
2. Have 'core' build a bootstrap when it reaches next 1000 height, enabled by API call (hardly any CPU but not immediate)

Building a bootstrap involves these steps:
1. delete all minting accounts from database (sensitive data)
2. delete all trade-bot entries from database (sensitive data)
3. remove all learned peers from database, leaving only the initial entries
4. perform "checkpoint defrag" to reduce database space usage
5. set database file timestamps to known value (e.g. timestamp of height block)
6. package into a ZIP

**Comment by QuickMythril** [comment]
Thank you.  This has been implemented, and can be closed / considered resolved.
