### ISSUE TITLE
Stores showing wrong products

### ISSUE THREAD

**Issue by TrendyKangaroo** [Qortal/qortal#130]
Hi, 

I have 2 stores. Sometimes store 1 shows the products from store 2 and vice versa. Sometimes my stores show no products and I have to go into the Product Manager, then go back to the storefront and then the correct products will show up.

**Comment by QuickMythril** [comment]
please use the Q-Apps repo for posting issues related to Q-Shop.
https://github.com/Qortal/Q-Apps/issues
