### ISSUE TITLE
stop.sh script doesn't check for curl

### ISSUE THREAD

**Issue by TRM13** [Qortal/qortal#28]
When you run the stop.sh script this is what you should see:

$ ./stop.sh 
Calling GET /admin/stop on local Qortal node
Qortal node responded and should be shutting down
Monitoring for Qortal node to end..
Qortal ended gracefully

But if you don't have curl installed it will do this:

$ ./stop.sh 
Calling GET /admin/stop on local Qortal node
No response from Qortal node - not running?

Simple wrapper to check for curl being in the path fixes that. I'm having too much fun with Markdown as the indentation is all messed up. Hope the text upload works. 

[stop.sh_Chk4curl.txt](https://github.com/Qortal/qortal/files/5969457/stop.sh_Chk4curl.txt)

**Comment by tcallahan14** [comment]
Thanks - this is a good improvement! I'll aim to get it included in a release soon.

**Comment by TRM13** [comment]
Let me know if there are any other scripting issues you want me to take on.

**Comment by CalDescent14** [comment]
Ok great - I'll let you know. Keep an eye on the #development channel in the Qortal discord if you can.

**Comment by TRM13** [comment]
Will do

**Comment by CalDescent14** [comment]
Thank you. I know that the project is in need of developers right now so anything you can help with will be appreciated.
