### ISSUE TITLE
Translation (Windows)

### ISSUE THREAD

**Issue by oldmagic** [Qortal/qortal#30]
Hello,

I just installed your wallet on my computer but when i start the program it fails to open completly.

"Translator:59 - Can't locate 'sv' translation resource bundle for SysTray"

And the UI from systray is looks like:
![axascacds](https://user-images.githubusercontent.com/1061791/107842870-b9050c00-6dc6-11eb-9d90-d152f7a11ed8.png)

**Comment by catbref** [comment]
The "!!sv:...!!" means there's no Swedish (sv) translation for a particular message.
Take a look at the files under src/main/resources/i18n/ and maybe contribute a Swedish version?

**Comment by QuickMythril** [comment]
Thank you for the feedback.  Swedish translations have been added to the Core.
This issue can be closed / considered resolved.
