### ISSUE TITLE
installing Qortal on Linux / Ubuntu, command line issues

### ISSUE THREAD

**Issue by 510N144** [Qortal/qortal#62]
Following the instructions on Qortal's website for installation on Linux **desktop only**, I've had success with all commands as listed except final command "sh ./start.sh" 

I get the response " Please su to non-root user before running"

I don't know what to do from here. I'm not a very command line savvy person, just starting out and don't really know much about terminal. When I open the Qortal UI, I get a repeated message: " connection to core lost " 
I would like to run a full node on my machine and begin minting and learning about all this wild new stuff! But alas, I am not that much of a computer savvy / nerd type. Please help me get my nerd on!

**Comment by Crojav** [comment]
> I get the response " Please su to non-root user before running"
It tells you that you have to be in admin mode so that you can start the core. But you dont need admin to start the core. Probably because the told you to start it with the sh shell.  I am on Linux it work in this way **bash start.sh** < see if this will help you

**Comment by QuickMythril** [comment]
The install instructions no longer appear to use the command referenced above.
I think this issue can be closed / considered resolved.
