### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by catbref** [Qortal/qortal#8]
More feedback required on this issue!

If you are affected by this, please comment with the following info:

* operating system, e.g. Windows/Linux/MacOS
* CPU, e.g. 1-core, 2-core; or more specific if you like, e.g. i7-7700, but always mention how many cores
* how much RAM, e.g. 16GB
* how you launch core, e.g. via desktop icon/start menu/EXE (same thing) or some batch file (please supply details)
* any changes you have made to your `settings.json` file, e.g. maxPeers, minOutboundPeers
* which version of core you are running
* whether your core can syncing/minting correctly, or not
* whether your core maintains connections to other peers, or not
* observed CPU load

Example:
* Linux
* Ryzen 3600 - 6 core/12 thread
* 16GB RAM
* `run.sh` script
* maxPeers set to 8
* v1.3.1
* can sync/mint ok
* can create/maintain 8 connections, doesn't vary much, if at all
* CPU usually 1% but spikes to 8% during sync/mint

**Comment by Caztiel** [comment]
- Windows
- i3-7100 - 2 core/4 thread (3.90Ghz)
- 4GB RAM (DDR4)
- Desktop Icon
- settings.json
  "apiDocumentationEnabled": false,
  "maxNetworkThreadPoolSize": 75,
  "minBlockchainPeers": 8,
  "minOutboundPeers": 10,
  "maxPeers": 22
- v1.3.1
- can sync/mint but its not stable.
- can create/maintain 8-10 connections, doesn't vary much, if at all
- CPU usually 70-80% during sync/mint

**Comment by marracc** [comment]
- Windows 7 x64
- AMD Athlon X4 860K Quad Core 4.10
- 8GB RAM
- Double click on qortal.exe
-   "minOutboundPeers": 10,
     "maxPeers": 10,
     "maxNetworkThreadPoolSize": 160 
- v1.3.1
- can sync/mint ok
- can create/maintain 10 connections. Blocks are going up and down. Minting status:
  18948 at 16:00. 18945 at 16:21 . 18983 at 17:03. Core is running all time
- CPU usually 30%-40% during sync/mint

**Comment by jdfreshman** [comment]
Windows 10 x64
XEON E3 1231V3  core4 
Double click on qortal.exe
"minOutboundPeers": 10,
"maxPeers": 16,
"maxNetworkThreadPoolSize": 160
v1.3.1
can sync/mint ok

CPU usually 30%-40% during sync/mint

**Comment by marracc** [comment]
- Windows 7 x64
- Intel Pentium Dual Core T4400 @2200 
- 4GB RAM
- Double click on qortal.exe
-   "minOutboundPeers": 5,
     "maxPeers": 8,
     "maxNetworkThreadPoolSize": 160 
- v1.3.1
- can sync. mint every now and then
- can create/maintain 10 connections. Minted blocks are going up and down. Hard to mint in constant, hard to stay with last node (syncs often)
- CPU usually 60%-80% during sync/mint
- problem with order canceling in UI, CPU to 100%, everything blocks and freezes, need to end process, order stayed

**Comment by Traxo7** [comment]
#### Vultr VPS node 1
|  | |  
| - | - |
| OS | Ubuntu 18.04 |
| CPU | 1 vCore |
| RAM | 2048 MB |
| settings | `{  "apiWhitelist": [...] }` |
| run cmd | `java -jar qortal.jar` 
| core version | 1.3.0 |
| can sync | yes | 
| can mint | yes |  

Maintains ~16 peers.  
CPU usage now 80% - 100%, used to be 25% - 50% week ago

#### Vultr VPS node 2  

|  | |  
| - | - |
| OS | Ubuntu 18.04 |
| CPU | 1 vCore |
| RAM | 1024 MB; 2GB swap |
| settings | `{  "apiWhitelist": [...], "maxPeers": 10 }` |
| run cmd | `java -Xmx2048M -jar target/qortal-1.3.1.jar` 
| core version | 1.3.1 |
| can sync | yes |
| can mint | not a minter | 

Maintains ~16 peers.  
CPU usage 75% - 100%

- - - 
https://exqlorer.com/peers  
Nodes are usually up to date (maybe just very few blocks behind sometimes, but apparently it's normal)

**Comment by JaymenChou** [comment]
Windows 10 x64
Intel i5 7200U @2.50GHz 2.70GHz, 2cores /4 threads
16GB RAM
Double click on qortal.exe
No specific setting on setting.json
32 connections
Synced
CPU usage is unstable at all.  From 2% - 40% (even it is not syncing)
Ram usage: around 500MB

**Comment by JoshuaFlood** [comment]
OS: Windows 10 Pro 64-bit

CPU: Ryzen 5 1500x 4 cores/8 threads

RAM: 24GB

Launch method: Start menu

Settings config:
```
{
  "apiWhitelist": [
      "::1",
      "127.0.0.1"
  ],
  "repositoryPath": "C:\\Users\\info\\AppData\\Local\\Qortal\\db",
  "apiDocumentationEnabled": true,
  "minBlockchainPeers": 10,
  "minOutboundPeers": 16,
  "maxPeers": 420
}
```
Core version: 1.3.3-3

Core runs fine for several hours. RAM usage gradually increases. Went to bed and woke up 7 hours later with 6GB RAM usage and 100% CPU. Before, on version 1.3.3-7 I never had any issues with CPU usage.
Syncing and minting works fine until CPU usage gets high, then the Core hangs. Displays Minting in the tooltip when you hover over the icon in the toolbar, but the 'block height' section within the UI is blank and the program is actually hanging, with no progress in block height being made.

**Comment by catbref** [comment]
A memory leak issue was addresses in v1.3.4 and CPU load should be lower in v1.3.5.
Can the people above report back whether the above nodes are performing better now please?

**Comment by Caztiel** [comment]
Can confirm it is working way better now in v1.3.5.

**Comment by QuickMythril** [comment]
Thank you for the feedback. This issue was addressed, and can be closed / considered resolved for now
