### ISSUE TITLE
Core should auto-fallback to IPv4 if IPv6 is not available

### ISSUE THREAD

**Issue by Nuc1eoN** [Qortal/qortal#96]
I have had quite some issues getting the core to run.
My last issue was was following when starting up the core (after bootstrapping etc was successful):
![image](https://user-images.githubusercontent.com/2538022/194649201-e47a692a-e33b-44df-8fb8-36675997383d.png)

It turned out this is because I have disabled IPv6 on my Linux system (iirc due to privacy reasons, but that shouldn't really matter).

I could work around this issue by adding:
```
"bindAddress":"0.0.0.0"
```
to the `settings.json`.

It is nice that it can be worked around, but ideally the core should recognize that issue and fallback to IPv4 automatically.

**Comment by CalDescent1** [comment]
Hi @Nuc1eoN

We do actually have a [branch](https://github.com/qortal/qortal/tree/bindaddress-ipv4) that does this but it was never merged. I think I might rewrite it anyway, so will try and get an auto fallback introduced in an upcoming release.

Cal

**Comment by Nuc1eoN** [comment]
Interesting! Thank you in advance :pray:

**Comment by QuickMythril** [comment]
Thank you for the feedback.  It appears this suggestion was implemented in the following commit:
https://github.com/Qortal/qortal/commit/358e67b05061849a5e4b148beaa185cca6a9dc75

I think that this issue can be closed / considered resolved.
